In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
import time
import requests

In [2]:
web='https://chromedriver.chromium.org/downloads'

In [3]:
driver=webdriver.Chrome(r'web')

In [4]:
driver.get("https://www.naukri.com/hr-recruiters-consultants")

In [5]:
search=driver.find_element(By.XPATH,'//*[@id="skill"]/div[1]/div[2]/input')
search.send_keys('Data Science')

In [6]:
cl=driver.find_element(By.XPATH,'//button[@class="fl qsbSrch blueBtn"]')
cl.click()

In [7]:
name = []
designation = []
company = []
skill = []
location = []

In [8]:
try:
    na=driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
    for i in na:
        name.append(i.text)
except NoSuchElementException:
        dl.append('-')

In [9]:
try:
    de=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
    for i in de:
        designation.append(i.text)
except NoSuchElementException:
        dl.append('-')

In [10]:
try:
    co=driver.find_elements(By.XPATH,'//a[@class="ellipsis"]')
    for i in co:
        company.append(i.text)
except NoSuchElementException:
        dl.append('-')

In [11]:
try:
    sk=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for i in sk:
        skill.append(i.text)
except NoSuchElementException:
        dl.append('-')

In [12]:
try:
    lo=driver.find_elements(By.XPATH,'//small[@class="ellipsis"]')
    for i in lo:
        location.append(i.text)
except NoSuchElementException:
        dl.append('-')

In [13]:
len(name),len(designation),len(company),len(skill),len(location)

(50, 50, 100, 50, 49)

In [14]:
df=pd.DataFrame({'NAME':name[0:40],'DESIGNATION':designation[0:40],'COMPANY':company[0:40],'SKILL':skill[0:40],'LOCATION':location[0:40]})
df

,NAME,DESIGNATION,COMPANY,SKILL,LOCATION
0,Aakash Harit,HR Manager,Aakash Harit,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Data Science Network,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,shravan Kumar Gaddam,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Shore Infotech India Pvt. Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,MARSIAN Technologies LLP,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,MARSIAN Technologies LLP,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,Anik Agrawal,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Enerlytics Software Solutions Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,subhas patel,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,LibraryXProject,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Abhishek - Only Analytics Hiring - India and,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,Apidel Technologies Division of Transpower,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,Institute for Financial Management and Resear,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,IFMR,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Priyanka Akiri,HR Manager,Balu Ramesh,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
15,Kapil Devang,HR Manager,Techvantage Systems Pvt Ltd,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Vaishnavi Kudalkar,HR Executive,Asif Lucknowi,"Data Science, Python, Data Analytics",Mumbai
17,Sakshi Chhikara,Assistant Manager HR,Weupskill- Live Wire India,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,InstaFinancials,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,CBL Data Science Private Limited,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Kalpana Dumpala,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,Innominds Software,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,Mubarak,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,MoneyTap,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Kushal Rastogi,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,QuantMagnum Technologies Pvt. Ltd.,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,Mahesh Babu Channa,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,SocialPrachar.com,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Priyanka Akiri,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,Infinitive Software Solutions,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Kapil Devang,"Signal Processing, Machine Learning, Neural Ne...",Delhi
31,Rajat Kumar,Founder CEO,BISP Solutions,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
32,Dhruv Dev Dubey,Company Recruitment Head,Vaishnavi Kudalkar,"Server Administartion, Verilog, Vhdl, Digital ...",Noida
33,Avnish Mishra,Senior Technical &amp; Corporate Recruiter,Codeachive learning,"Data Science, Machine Learning, Deep Learning,...",Mysoru / Mysore
34,Jayanth N,Project Manager,Sakshi Chhikara,"Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
35,Avodha,Business Development Associate,BIZ INFOTECNO PRIVATE LIMITED,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
36,Priya Khare,Senior Manager,Ruchi Dhote,"Data Science, Artificial Intelligence, analyti...",New Delhi
37,Amit Sharma,Consultant,Bristlecone India Ltd,"Machine Learning, Artificial Intelligence, Dat...",Chennai
38,Kanan,senior technology instructor,Manisha Yadav,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,Easi Tax,"Relationship Management, Retail Sales, Private...",Salt Lake City

In [15]:
driver.close()